use super::report::RtkStatus;

/// A rule mapping a shell command pattern to its RTK equivalent.
pub struct RtkRule {
    pub rtk_cmd: &'static str,
    /// Original command prefixes to replace with rtk_cmd (longest first for correct matching).
    pub rewrite_prefixes: &'static [&'static str],
    pub category: &'static str,
    pub savings_pct: f64,
    pub subcmd_savings: &'static [(&'static str, f64)],
    pub subcmd_status: &'static [(&'static str, RtkStatus)],
}

// Patterns ordered to match RULES indices exactly.
pub const PATTERNS: &[&str] = &[
    r"^git\s+(?:(?:-[cC]\s+\S+\s+)*)?(status|log|diff|show|add|commit|push|pull|branch|fetch|stash|worktree|checkout|merge|rebase|reset|tag|remote|clone|init|mv|rm|restore|switch|revert|clean|bisect|blame|cherry-pick|reflog|config|submodule|ls-files|rev-parse|check-ignore|describe|shortlog|grep|archive|notes|gc|rev-list|for-each-ref|ls-remote|ls-tree|name-rev|symbolic-ref|update-ref|am|format-patch|subtree)",
    r"^gh\s+(pr|issue|run|repo|api|release)",
    r"^cargo\s+(build|test|clippy|check|fmt|install|tree|doc|bench|clean|update|publish|add|remove)",
    r"^pnpm\s+(?:(?:--filter|-F)\s+\S+\s+|(?:--recursive|-r|-w|--workspace-root)\s+)*(list|ls|outdated|install|build|exec|run|typecheck|test|dev|start|add|remove|update|dlx|create|why|audit|publish|link|store)",
    r"^npm\s+(run|exec|test|install|ci|start|build|publish|pack|link|unlink|update|outdated|ls|list|audit|fund|why|cache|config|init|version|view|info|search|deprecate)",
    r"^npx\s+",
    r"^(cat|head|tail)\s+",
    r"^(rg|grep)\s+",
    r"^ls(\s|$)",
    r"^find\s+",
    r"^(npx\s+|pnpm\s+)?tsc(\s|$)",
    r"^(npx\s+|pnpm\s+)?(eslint|biome|lint)(\s|$)",
    r"^(npx\s+|pnpm\s+)?prettier",
    r"^(npx\s+|pnpm\s+)?next\s+build",
    r"^(pnpm\s+|npx\s+)?(vitest|jest|test)(\s|$)",
    r"^(npx\s+|pnpm\s+)?playwright",
    r"^(npx\s+|pnpm\s+)?prisma",
    r"^docker\s+(ps|images|logs|run|exec|build|compose\s+(ps|logs|build))",
    r"^kubectl\s+(get|logs|describe|apply)",
    r"^tree(\s|$)",
    r"^diff\s+",
    r"^curl\s+",
    r"^wget\s+",
    r"^(python3?\s+-m\s+)?mypy(\s|$)",
    // Python tooling
    r"^ruff\s+(check|format)",
    r"^(python\s+-m\s+)?pytest(\s|$)",
    r"^(pip3?|uv\s+pip)\s+(list|outdated|install)",
    // Go tooling
    r"^go\s+(test|build|vet|mod|tool|run|fmt|generate|install|get|clean|env|doc|list)",
    r"^golangci-lint(\s|$)",
    // AWS CLI
    r"^aws\s+",
    // PostgreSQL
    r"^psql(\s|$)",
    // TOML-filtered commands
    r"^ansible-playbook\b",
    r"^brew\s+(install|upgrade)\b",
    r"^composer\s+(install|update|require)\b",
    r"^df(\s|$)",
    r"^dotnet\s+build\b",
    r"^du\b",
    r"^fail2ban-client\b",
    r"^gcloud\b",
    r"^hadolint\b",
    r"^helm\b",
    r"^iptables\b",
    r"^make\b",
    r"^markdownlint\b",
    r"^mix\s+(compile|format)(\s|$)",
    r"^mvn\s+(compile|package|clean|install)\b",
    r"^ping\b",
    r"^pio\s+run",
    r"^poetry\s+(install|lock|update)\b",
    r"^pre-commit\b",
    r"^ps(\s|$)",
    r"^quarto\s+render",
    r"^rsync\b",
    r"^shellcheck\b",
    r"^shopify\s+theme\s+(push|pull)",
    r"^sops\b",
    r"^swift\s+build\b",
    r"^systemctl\s+status\b",
    r"^terraform\s+plan",
    r"^tofu\s+(fmt|init|plan|validate)(\s|$)",
    r"^trunk\s+build",
    r"^uv\s+(sync|pip\s+install)\b",
    r"^yamllint\b",
];

pub const RULES: &[RtkRule] = &[
    RtkRule {
        rtk_cmd: "rtk git",
        rewrite_prefixes: &["git"],
        category: "Git",
        savings_pct: 70.0,
        subcmd_savings: &[
            ("diff", 80.0),
            ("show", 80.0),
            ("add", 59.0),
            ("commit", 59.0),
        ],
        subcmd_status: &[
            ("checkout", RtkStatus::Passthrough),
            ("merge", RtkStatus::Passthrough),
            ("rebase", RtkStatus::Passthrough),
            ("reset", RtkStatus::Passthrough),
            ("tag", RtkStatus::Passthrough),
            ("remote", RtkStatus::Passthrough),
            ("clone", RtkStatus::Passthrough),
            ("init", RtkStatus::Passthrough),
            ("mv", RtkStatus::Passthrough),
            ("rm", RtkStatus::Passthrough),
            ("restore", RtkStatus::Passthrough),
            ("switch", RtkStatus::Passthrough),
            ("revert", RtkStatus::Passthrough),
            ("clean", RtkStatus::Passthrough),
            ("bisect", RtkStatus::Passthrough),
            ("blame", RtkStatus::Passthrough),
            ("cherry-pick", RtkStatus::Passthrough),
            ("reflog", RtkStatus::Passthrough),
            ("config", RtkStatus::Passthrough),
            ("submodule", RtkStatus::Passthrough),
            ("ls-files", RtkStatus::Passthrough),
            ("rev-parse", RtkStatus::Passthrough),
            ("check-ignore", RtkStatus::Passthrough),
            ("describe", RtkStatus::Passthrough),
            ("shortlog", RtkStatus::Passthrough),
            ("grep", RtkStatus::Passthrough),
            ("archive", RtkStatus::Passthrough),
            ("notes", RtkStatus::Passthrough),
            ("gc", RtkStatus::Passthrough),
            ("rev-list", RtkStatus::Passthrough),
            ("for-each-ref", RtkStatus::Passthrough),
            ("ls-remote", RtkStatus::Passthrough),
            ("ls-tree", RtkStatus::Passthrough),
            ("name-rev", RtkStatus::Passthrough),
            ("symbolic-ref", RtkStatus::Passthrough),
            ("update-ref", RtkStatus::Passthrough),
            ("am", RtkStatus::Passthrough),
            ("format-patch", RtkStatus::Passthrough),
            ("subtree", RtkStatus::Passthrough),
        ],
    },
    RtkRule {
        rtk_cmd: "rtk gh",
        rewrite_prefixes: &["gh"],
        category: "GitHub",
        savings_pct: 82.0,
        subcmd_savings: &[("pr", 87.0), ("run", 82.0), ("issue", 80.0)],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk cargo",
        rewrite_prefixes: &["cargo"],
        category: "Cargo",
        savings_pct: 80.0,
        subcmd_savings: &[
            ("test", 90.0),
            ("check", 80.0),
            ("tree", 40.0),
            ("doc", 30.0),
            ("bench", 50.0),
        ],
        subcmd_status: &[
            ("fmt", RtkStatus::Passthrough),
            ("tree", RtkStatus::Passthrough),
            ("doc", RtkStatus::Passthrough),
            ("bench", RtkStatus::Passthrough),
            ("clean", RtkStatus::Passthrough),
            ("update", RtkStatus::Passthrough),
            ("publish", RtkStatus::Passthrough),
            ("add", RtkStatus::Passthrough),
            ("remove", RtkStatus::Passthrough),
        ],
    },
    RtkRule {
        rtk_cmd: "rtk pnpm",
        rewrite_prefixes: &["pnpm"],
        category: "PackageManager",
        savings_pct: 80.0,
        subcmd_savings: &[
            ("build", 40.0),
            ("exec", 35.0),
            ("run", 40.0),
            ("typecheck", 50.0),
        ],
        subcmd_status: &[
            ("build", RtkStatus::Passthrough),
            ("exec", RtkStatus::Passthrough),
            ("run", RtkStatus::Passthrough),
            ("typecheck", RtkStatus::Passthrough),
            ("test", RtkStatus::Passthrough),
            ("dev", RtkStatus::Passthrough),
            ("start", RtkStatus::Passthrough),
            ("add", RtkStatus::Passthrough),
            ("remove", RtkStatus::Passthrough),
            ("update", RtkStatus::Passthrough),
            ("dlx", RtkStatus::Passthrough),
            ("create", RtkStatus::Passthrough),
            ("why", RtkStatus::Passthrough),
            ("audit", RtkStatus::Passthrough),
            ("publish", RtkStatus::Passthrough),
            ("link", RtkStatus::Passthrough),
            ("store", RtkStatus::Passthrough),
        ],
    },
    RtkRule {
        rtk_cmd: "rtk npm",
        rewrite_prefixes: &["npm"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[("test", 50.0), ("install", 40.0), ("ci", 40.0)],
        subcmd_status: &[
            ("test", RtkStatus::Passthrough),
            ("install", RtkStatus::Passthrough),
            ("ci", RtkStatus::Passthrough),
            ("start", RtkStatus::Passthrough),
            ("build", RtkStatus::Passthrough),
            ("publish", RtkStatus::Passthrough),
            ("pack", RtkStatus::Passthrough),
            ("link", RtkStatus::Passthrough),
            ("unlink", RtkStatus::Passthrough),
            ("update", RtkStatus::Passthrough),
            ("outdated", RtkStatus::Passthrough),
            ("ls", RtkStatus::Passthrough),
            ("list", RtkStatus::Passthrough),
            ("audit", RtkStatus::Passthrough),
            ("fund", RtkStatus::Passthrough),
            ("why", RtkStatus::Passthrough),
            ("cache", RtkStatus::Passthrough),
            ("config", RtkStatus::Passthrough),
            ("init", RtkStatus::Passthrough),
            ("version", RtkStatus::Passthrough),
            ("view", RtkStatus::Passthrough),
            ("info", RtkStatus::Passthrough),
            ("search", RtkStatus::Passthrough),
            ("deprecate", RtkStatus::Passthrough),
        ],
    },
    RtkRule {
        rtk_cmd: "rtk npx",
        rewrite_prefixes: &["npx"],
        category: "PackageManager",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk read",
        rewrite_prefixes: &["cat", "head", "tail"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk grep",
        rewrite_prefixes: &["rg", "grep"],
        category: "Files",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk ls",
        rewrite_prefixes: &["ls"],
        category: "Files",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk find",
        rewrite_prefixes: &["find"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        // Longest prefixes first for correct matching
        rtk_cmd: "rtk tsc",
        rewrite_prefixes: &["pnpm tsc", "npx tsc", "tsc"],
        category: "Build",
        savings_pct: 83.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk lint",
        rewrite_prefixes: &[
            "npx eslint",
            "pnpm lint",
            "npx biome",
            "eslint",
            "biome",
            "lint",
        ],
        category: "Build",
        savings_pct: 84.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk prettier",
        rewrite_prefixes: &["npx prettier", "pnpm prettier", "prettier"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        // "next build" is stripped to "rtk next" — the build subcommand is internal
        rtk_cmd: "rtk next",
        rewrite_prefixes: &["npx next build", "pnpm next build", "next build"],
        category: "Build",
        savings_pct: 87.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk vitest",
        rewrite_prefixes: &["pnpm vitest", "npx vitest", "vitest", "jest"],
        category: "Tests",
        savings_pct: 99.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk playwright",
        rewrite_prefixes: &["npx playwright", "pnpm playwright", "playwright"],
        category: "Tests",
        savings_pct: 94.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk prisma",
        rewrite_prefixes: &["npx prisma", "pnpm prisma", "prisma"],
        category: "Build",
        savings_pct: 88.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk docker",
        rewrite_prefixes: &["docker"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk kubectl",
        rewrite_prefixes: &["kubectl"],
        category: "Infra",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk tree",
        rewrite_prefixes: &["tree"],
        category: "Files",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk diff",
        rewrite_prefixes: &["diff"],
        category: "Files",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk curl",
        rewrite_prefixes: &["curl"],
        category: "Network",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk wget",
        rewrite_prefixes: &["wget"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk mypy",
        rewrite_prefixes: &["python3 -m mypy", "python -m mypy", "mypy"],
        category: "Build",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // Python tooling
    RtkRule {
        rtk_cmd: "rtk ruff",
        rewrite_prefixes: &["ruff"],
        category: "Python",
        savings_pct: 80.0,
        subcmd_savings: &[("check", 80.0), ("format", 75.0)],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk pytest",
        rewrite_prefixes: &["python -m pytest", "pytest"],
        category: "Python",
        savings_pct: 90.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk pip",
        rewrite_prefixes: &["pip3", "pip", "uv pip"],
        category: "Python",
        savings_pct: 75.0,
        subcmd_savings: &[("list", 75.0), ("outdated", 80.0)],
        subcmd_status: &[],
    },
    // Go tooling
    RtkRule {
        rtk_cmd: "rtk go",
        rewrite_prefixes: &["go"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[
            ("test", 90.0),
            ("build", 80.0),
            ("vet", 75.0),
            ("mod", 35.0),
            ("tool", 30.0),
            ("doc", 40.0),
            ("list", 40.0),
        ],
        subcmd_status: &[
            ("mod", RtkStatus::Passthrough),
            ("tool", RtkStatus::Passthrough),
            ("run", RtkStatus::Passthrough),
            ("fmt", RtkStatus::Passthrough),
            ("generate", RtkStatus::Passthrough),
            ("install", RtkStatus::Passthrough),
            ("get", RtkStatus::Passthrough),
            ("clean", RtkStatus::Passthrough),
            ("env", RtkStatus::Passthrough),
            ("doc", RtkStatus::Passthrough),
            ("list", RtkStatus::Passthrough),
        ],
    },
    RtkRule {
        rtk_cmd: "rtk golangci-lint",
        rewrite_prefixes: &["golangci-lint", "golangci"],
        category: "Go",
        savings_pct: 85.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // AWS CLI
    RtkRule {
        rtk_cmd: "rtk aws",
        rewrite_prefixes: &["aws"],
        category: "Infra",
        savings_pct: 80.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // PostgreSQL
    RtkRule {
        rtk_cmd: "rtk psql",
        rewrite_prefixes: &["psql"],
        category: "Infra",
        savings_pct: 75.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    // TOML-filtered commands
    RtkRule {
        rtk_cmd: "rtk ansible-playbook",
        rewrite_prefixes: &["ansible-playbook"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk brew",
        rewrite_prefixes: &["brew"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk composer",
        rewrite_prefixes: &["composer"],
        category: "PackageManager",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk df",
        rewrite_prefixes: &["df"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk dotnet",
        rewrite_prefixes: &["dotnet"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk du",
        rewrite_prefixes: &["du"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk fail2ban-client",
        rewrite_prefixes: &["fail2ban-client"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk gcloud",
        rewrite_prefixes: &["gcloud"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk hadolint",
        rewrite_prefixes: &["hadolint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk helm",
        rewrite_prefixes: &["helm"],
        category: "Infra",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk iptables",
        rewrite_prefixes: &["iptables"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk make",
        rewrite_prefixes: &["make"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk markdownlint",
        rewrite_prefixes: &["markdownlint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk mix",
        rewrite_prefixes: &["mix"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk mvn",
        rewrite_prefixes: &["mvn"],
        category: "Build",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk ping",
        rewrite_prefixes: &["ping"],
        category: "Network",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk pio",
        rewrite_prefixes: &["pio"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk poetry",
        rewrite_prefixes: &["poetry"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk pre-commit",
        rewrite_prefixes: &["pre-commit"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk ps",
        rewrite_prefixes: &["ps"],
        category: "System",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk quarto",
        rewrite_prefixes: &["quarto"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk rsync",
        rewrite_prefixes: &["rsync"],
        category: "Network",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk shellcheck",
        rewrite_prefixes: &["shellcheck"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk shopify",
        rewrite_prefixes: &["shopify"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk sops",
        rewrite_prefixes: &["sops"],
        category: "Infra",
        savings_pct: 60.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk swift",
        rewrite_prefixes: &["swift"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk systemctl",
        rewrite_prefixes: &["systemctl"],
        category: "System",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk terraform",
        rewrite_prefixes: &["terraform"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk tofu",
        rewrite_prefixes: &["tofu"],
        category: "Infra",
        savings_pct: 70.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk trunk",
        rewrite_prefixes: &["trunk"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk uv",
        rewrite_prefixes: &["uv"],
        category: "Python",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
    RtkRule {
        rtk_cmd: "rtk yamllint",
        rewrite_prefixes: &["yamllint"],
        category: "Build",
        savings_pct: 65.0,
        subcmd_savings: &[],
        subcmd_status: &[],
    },
];

/// Commands to ignore (shell builtins, trivial, already rtk).
pub const IGNORED_PREFIXES: &[&str] = &[
    "cd ",
    "cd\t",
    "echo ",
    "printf ",
    "export ",
    "source ",
    "mkdir ",
    "rm ",
    "mv ",
    "cp ",
    "chmod ",
    "chown ",
    "touch ",
    "which ",
    "type ",
    "command ",
    "test ",
    "true",
    "false",
    "sleep ",
    "wait",
    "kill ",
    "set ",
    "unset ",
    "wc ",
    "sort ",
    "uniq ",
    "tr ",
    "cut ",
    "awk ",
    "sed ",
    "python3 -c",
    "python -c",
    "node -e",
    "ruby -e",
    "rtk ",
    "pwd",
    "bash ",
    "sh ",
    "then\n",
    "then ",
    "else\n",
    "else ",
    "do\n",
    "do ",
    "for ",
    "while ",
    "if ",
    "case ",
    // Python scripts (not commands)
    "python3 \"",
    "python \"",
    "python3 ./",
    "python ./",
    "python3 ../",
    "python ../",
    // Node (not npm/npx commands)
    "node -p",
    "node --check",
    "node ./",
    "node .",
    // Windows system commands
    "powershell",
    "pwsh",
    "cmd",
    "dir",
    "rmdir",
    "del",
    "netstat",
    "ipconfig",
    "systeminfo",
    "reg ",
    "where ",
    "whoami",
    "hostname",
    "sc ",
    "wmic",
    "icacls",
    "attrib",
    "certutil",
    "schtasks",
    "net ",
    // Trivial commands
    "tasklist",
    "taskkill",
    "TASKLIST",
    "TASKKILL",
    "cmp ",
    "timeout",
    "tee ",
    // Version checks (trivial output)
    "go version",
    "python --version",
    "python3 --version",
    "rustc --",
    "npm root",
    // Unix utilities
    "xxd",
    "file ",
    "stat ",
    "uname",
    "date",
    "id ",
    // Custom executables
    "./bin/",
    ".\\bin\\",
    ".venv/",
    ".venv\\",
];

pub const IGNORED_EXACT: &[&str] = &[
    "cd", "echo", "true", "false", "wait", "pwd", "bash", "sh", "fi", "done", "env", "printenv",
    "whoami", "hostname", "date", "id", "uname",
];
